name: london-crime-mixtures
channels:
  - conda-forge
  - conda

dependencies:
  - gcc_linux-64
  - gsl
  - gmp
  - mpfr
  - yaml
  - PyYAML
  - pytest
  - click
  - Sphinx
  - coverage
  - flake8
  - python-dotenv>=0.5.1
  - numpy
  - scipy
  - numba
  - pandas
  - matplotlib
  - seaborn
  - geopandas
  - pysal
  - gdal
  - contextily
  - corner
  - scikit-learn
  - jupyterhub
  - nb_conda
  - nodejs # for extensions
