covariates:
 - "intercept"
 - "log.household.count"
# - "unemployment.percent"
# - "log.poi.retail.count"
# - "log.poi.eatdrink.count"
# - "log.poi.edu.health.count"
# - "log.poi.accommodation.count"
# - "log.poi.sport.entertainment.count"
 - "log.poi.all"
 - "ethnic.heterogeneity"
# - "median.age"
 - "accessibility"
 - "population.turnover"
# - "all.houses.fraction"
# - "detached.houses.fraction"
# - "semidetached.houses.fraction"
# - "terraced.houses.fraction"
 - "detached.semidetached.houses.fraction"
 - "occupation.variation"
# - "tenure.owned.fraction"
# - "tenure.rented.social.fraction"
# - "tenure.rented.private.fraction"
# - "tenure.other.fraction"
# - "single.parent.household.fraction"
# - "one.person.household.fraction"
# - "couple.with.children.fraction"
# - "log.mean.hh.income"
 - "log.house.price"
# - "urban.proportion"
# - "urban.suburban.proportion"
covariates_to_log:

# diff 2
 # remove tenure-owned due to correlation with all houses (.78) and (semi-)detached houses (.72). Also theoreticallt not much basis for it
 # remove urban proportion (no basis)
 # remove single parent due to high correlation with tenure-social (.65) and unemployment (.62)
 # remove all houses due to correlation with (semi-)detached houses (.75) and more theoretical backing for the other one


# diff 3
 # remove median age due to no strong theoretical backing
 # remove one-person household due to no strong evidence
 # remove household income due to low evidence from other studies and already covering it with house price (corr 0.83)
 # remove tenure rented social due to not very strong theoretical backing and correlation with unemployment (.62)
 # remove accommodation POIs due to weak empirical evidence from previous studies


# diff 4
 # remove unemployment rate due to weak empirical support from previous studies
 # bunch up the POIs so that they are not correlated with each other.
