covariates:
 - "intercept"
 - "log.household.count"
 - "unemployment.percent"
 - "log.poi.retail.count"
 - "log.poi.eatdrink.count"
 - "log.poi.edu.health.count"
 - "log.poi.accommodation.count"
 - "log.poi.sport.entertainment.count"
# - "log.poi.all"
 - "ethnic.heterogeneity"
 - "median.age"
 - "accessibility"
 - "population.turnover"
# - "all.houses.fraction"
# - "detached.houses.fraction"
# - "semidetached.houses.fraction"
# - "terraced.houses.fraction"
 - "detached.semidetached.houses.fraction"
 - "occupation.variation"
# - "tenure.owned.fraction"
 - "tenure.rented.social.fraction"
# - "tenure.rented.private.fraction"
# - "tenure.other.fraction"
# - "single.parent.household.fraction"
 - "one.person.household.fraction"
# - "couple.with.children.fraction"
 - "log.mean.hh.income"
 - "log.house.price"
# - "urban.proportion"
covariates_to_log:

# diff 2
 # remove tenure-owned due to correlation with all houses (.79) and (semi-)detached houses (.72). Also theoretically not much basis for it
 # remove urban proportion (no basis)
 # remove single parent due to high correlation with tenure-social (.65) and unemployment (.62)
 # remove all houses due to correlation with (semi-)detached houses (.75) and more theoretical backing for the other one
